# Generated by Django 5.0.6 on 2024-10-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
